#\u7533\u8bf7\u540e\u83b7\u53d6client_id\u548cclient_secret
#client_id=73883
client_id=97328
#client_secret=AzkckHblDuxWXW1qn9b1xVuWklnoluyx
client_secret=kTcK3WZTLjeURjrA73AVDIRCs186J2OU
redirect_uri=http://192.168.32.30:8080/umtOauthDemo/testtoken
#\u56fa\u5b9a\u503c
#access_token_URL=https://login.ihep.ac.cn/oauth2/token
#authorize_URL=https://login.ihep.ac.cn/oauth2/authorize
access_token_URL=https://192.168.32.30:8080/oauth2/token
authorize_URL=https://192.168.32.30:8080/oauth2/authorize
#authorize_URL=https://passport.escience.cn/oauth2/authorize  
scope=
#theme \u5171\u4e09\u79cd\u7c7b\u578bsimple/full/embed
theme=simple